version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: "go_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: "go_redis"
    ports:
      - 6379:6379
    volumes:
      - ./db/redis_data:/data
    command: redis-server --appendonly yes
